version: '3.8'

services:
  backend:
    image: aryansarvaiya13/cloudlab-backend:latest
    container_name: cloudlab-backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    restart: unless-stopped

  frontend:
    image: aryansarvaiya13/cloudlab-frontend:latest
    container_name: cloudlab-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
