version: "3.8"

services:
  backend:
    image: aryansarvaiya13/cloudlab-backend:latest
    container_name: cloudlab-backend
    ports:
      - "5000:5000"
    env_file:
      - backend/.env
    restart: unless-stopped
    networks:
      - cloudlab-net

  frontend:
    image: aryansarvaiya13/cloudlab-frontend:latest
    container_name: cloudlab-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - cloudlab-net

  prometheus:
    image: prom/prometheus:latest
    container_name: cloudlab-prometheus
    ports:
      - "9091:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - cloudlab-net

  grafana:
    image: grafana/grafana:latest
    container_name: cloudlab-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    restart: unless-stopped
    networks:
      - cloudlab-net

networks:
  cloudlab-net:
    driver: bridge
